/**
 * Known actors: militaries, armed groups, governments, leaders, organisations.
 * [name, subtype, country/bloc, ...aliases]. Neutral names (each group under the
 * name it is commonly reported by, with its own name as an alias); extend freely.
 * Rules-based extraction matches these in every entry; Claude finds the rest.
 */
export type ActorRow = [name: string, subtype: 'military' | 'armed-group' | 'government' | 'person' | 'org' | 'party', country: string, ...aliases: string[]]

export const ACTORS: ActorRow[] = [
  // militaries and security forces
  ['Russian Armed Forces', 'military', 'RU', 'Russian forces', 'Russian army', 'Russian troops', 'Russian military', 'Russian MoD', 'Russian Defence Ministry', 'ВС РФ', 'Минобороны России'],
  ['Ukrainian Armed Forces', 'military', 'UA', 'Ukrainian forces', 'Ukrainian army', 'Ukrainian troops', 'Ukrainian military', 'AFU', 'ZSU', 'ЗСУ', 'ВСУ'],
  ['Israel Defense Forces', 'military', 'IL', 'IDF', 'Israeli army', 'Israeli military', 'Israeli forces', 'Israeli troops', 'צה"ל'],
  ['IRGC', 'military', 'IR', 'Islamic Revolutionary Guard Corps', 'Revolutionary Guards', 'سپاه'],
  ['Iranian Armed Forces', 'military', 'IR', 'Iranian army', 'Iranian military', 'Iranian forces'],
  ['US Armed Forces', 'military', 'US', 'US military', 'US forces', 'US troops', 'Pentagon', 'US Navy', 'US Air Force', 'CENTCOM', 'US Army'],
  ['NATO', 'org', 'NATO', 'North Atlantic Treaty Organization', 'НАТО'],
  ['Saudi-led coalition', 'military', 'SA', 'Saudi coalition', 'Saudi forces', 'Saudi military', 'Saudi Arabian forces'],
  ['Pakistan Armed Forces', 'military', 'PK', 'Pakistani army', 'Pakistani military', 'Pakistani forces', 'ISPR'],
  ['Indian Armed Forces', 'military', 'IN', 'Indian army', 'Indian military', 'Indian forces'],
  ['Chinese PLA', 'military', 'CN', 'PLA', "People's Liberation Army", 'Chinese military', 'Chinese navy'],
  ['North Korean military', 'military', 'KP', 'KPA', "Korean People's Army", 'North Korean army'],
  ['Sudanese Armed Forces', 'military', 'SD', 'SAF', 'Sudanese army'],
  ['Ethiopian National Defense Force', 'military', 'ET', 'ENDF', 'Ethiopian forces', 'Ethiopian army', 'Ethiopian troops'],
  ['Turkish Armed Forces', 'military', 'TR', 'Turkish army', 'Turkish military', 'Turkish forces'],
  ['Syrian government forces', 'military', 'SY', 'Syrian army', 'Syrian forces'],
  ['Lebanese Army', 'military', 'LB', 'Lebanese Armed Forces', 'LAF'],
  ['Yemeni government forces', 'military', 'YE', 'Yemeni forces', "Yemen's armed forces", 'Yemeni army'],
  // armed groups and movements
  ['Hamas', 'armed-group', 'PS', 'Qassam Brigades', 'al-Qassam', 'حماس'],
  ['Palestinian Islamic Jihad', 'armed-group', 'PS', 'Islamic Jihad', 'PIJ', 'al-Quds Brigades'],
  ['Hezbollah', 'armed-group', 'LB', 'Hizbollah', 'Hizballah', 'حزب الله'],
  ['Houthis', 'armed-group', 'YE', 'Ansar Allah', 'Ansarallah', 'Houthi', 'أنصار الله', 'الحوثيون'],
  ['Rapid Support Forces', 'armed-group', 'SD', 'RSF'],
  ['Wagner Group', 'armed-group', 'RU', 'Wagner', 'Africa Corps', 'ЧВК Вагнер'],
  ['Taliban', 'government', 'AF', 'Islamic Emirate of Afghanistan', 'Taliban government'],
  ['TTP', 'armed-group', 'PK', 'Tehrik-i-Taliban Pakistan', 'Pakistani Taliban'],
  ['Islamic State', 'armed-group', 'INT', 'ISIS', 'ISIL', 'Daesh', 'داعش'],
  ['ISWAP', 'armed-group', 'NG', 'Islamic State West Africa', 'Islamic State West Africa Province'],
  ['Boko Haram', 'armed-group', 'NG'],
  ['al-Shabaab', 'armed-group', 'SO', 'al Shabaab', 'Al-Shabab', 'Shabaab'],
  ['JNIM', 'armed-group', 'ML', 'Jama\'at Nusrat al-Islam wal-Muslimin'],
  ['M23', 'armed-group', 'CD', 'March 23 Movement', 'AFC/M23'],
  ['TPLF', 'armed-group', 'ET', "Tigray People's Liberation Front", 'Tigrayan forces'],
  ['PKK', 'armed-group', 'TR', "Kurdistan Workers' Party"],
  ['SDF', 'armed-group', 'SY', 'Syrian Democratic Forces'],
  ['HTS', 'armed-group', 'SY', 'Hayat Tahrir al-Sham'],
  ['Kataib Hezbollah', 'armed-group', 'IQ', 'Islamic Resistance in Iraq'],
  ['Baloch Liberation Army', 'armed-group', 'PK', 'BLA'],
  ['Arakan Army', 'armed-group', 'MM'],
  ['Myanmar military', 'military', 'MM', 'Tatmadaw'],
  ['Haitian gangs', 'armed-group', 'HT', 'Viv Ansanm', 'G9'],
  // governments and institutions
  ['Kremlin', 'government', 'RU', 'Russian government', 'Кремль'],
  ['Government of Ukraine', 'government', 'UA', 'Ukrainian government', 'Kyiv government'],
  ['Government of Israel', 'government', 'IL', 'Israeli government'],
  ['Government of Iran', 'government', 'IR', 'Iranian government', 'Tehran government'],
  ['US government', 'government', 'US', 'White House', 'State Department', 'US administration'],
  ['Chinese government', 'government', 'CN', 'Beijing government', 'Chinese foreign ministry'],
  ['Saudi government', 'government', 'SA', 'Riyadh government', 'Saudi Arabia government'],
  ['European Union', 'org', 'EU', 'EU', 'European Commission'],
  ['United Nations', 'org', 'UN', 'UN', 'UN Security Council', 'UNSC', 'UNHCR', 'UNRWA', 'OCHA', 'ООН'],
  ['IAEA', 'org', 'UN', 'International Atomic Energy Agency'],
  ['ICC', 'org', 'INT', 'International Criminal Court'],
  ['Red Cross', 'org', 'INT', 'ICRC', 'Red Crescent'],
  ['African Union', 'org', 'AU', 'AU'],
  // people (current leaders and frequent newsmakers)
  ['Vladimir Putin', 'person', 'RU', 'Putin', 'Путин'],
  ['Volodymyr Zelensky', 'person', 'UA', 'Zelensky', 'Zelenskyy', 'Зеленський', 'Зеленский'],
  ['Benjamin Netanyahu', 'person', 'IL', 'Netanyahu'],
  ['Ali Khamenei', 'person', 'IR', 'Khamenei', 'خامنه‌ای'],
  ['Donald Trump', 'person', 'US', 'Trump'],
  ['Xi Jinping', 'person', 'CN', 'Xi'],
  ['Recep Tayyip Erdogan', 'person', 'TR', 'Erdogan', 'Erdoğan'],
  ['Mohammed bin Salman', 'person', 'SA', 'MBS', 'bin Salman'],
  ['Kim Jong Un', 'person', 'KP', 'Kim Jong-un', 'Kim Jong Un'],
  ['Narendra Modi', 'person', 'IN', 'Modi'],
  ['Shehbaz Sharif', 'person', 'PK', 'Sharif'],
  ['Ilham Aliyev', 'person', 'AZ', 'Aliyev'],
  ['Abdel Fattah al-Burhan', 'person', 'SD', 'Burhan'],
  ['Mohamed Hamdan Dagalo', 'person', 'SD', 'Hemedti'],
  ['Abdul-Malik al-Houthi', 'person', 'YE'],
  ['Naim Qassem', 'person', 'LB'],
  ['Emmanuel Macron', 'person', 'FR', 'Macron'],
  ['Keir Starmer', 'person', 'GB', 'Starmer'],
  ['Friedrich Merz', 'person', 'DE', 'Merz'],
  ['Sergey Lavrov', 'person', 'RU', 'Lavrov', 'Лавров'],
  ['Masoud Pezeshkian', 'person', 'IR', 'Pezeshkian'],
  ['Javier Milei', 'person', 'AR', 'Milei'],
  ['Bobi Wine', 'person', 'UG', 'Robert Kyagulanyi'],
  ['Yoweri Museveni', 'person', 'UG', 'Museveni'],
]
